"use strict";

/*
|--------------------------------------------------------------------------
| ClienteSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use("Factory");
const Cliente = use("App/Models/Cliente");
class ClienteSeeder {
  async run() {
    await Cliente.createMany([
      {
        nome: "Hellen Monte Candeias",
        cpf: "06229541256",
        email: "hellen@email.com",
        telefone: "99355-5656",
        cep: "72220365",
        logradouro: "Rua 222",
        numero_lote: "42",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Ceilândia Sul",
        uf: "DF",
      },
      {
        nome: "Vitor Vital Palmeira",
        cpf: "12336595214",
        email: "vitor@email.com",
        telefone: "99523-6521",
        cep: "72665851",
        logradouro: "Quadra 01 Rua 3",
        numero_lote: "16",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Ceilândia Norte",
        uf: "DF",
      },
      {
        nome: "Ludmila Boeira Camelo",
        cpf: "41225963214",
        email: "ludmila@email.com",
        telefone: "99010-1010",
        cep: "72659101",
        logradouro: "QNN 23",
        numero_lote: "33",
        complemento: "Casa",
        cidade: "Taguatinga",
        bairro: "Taguatinga Sul",
        uf: "DF",
      },
      {
        nome: "Antero Malafaia Simões",
        cpf: "42551236258",
        email: "anteno@email.com",
        telefone: "99236-6523",
        cep: "72321420",
        logradouro: "QNO 29",
        numero_lote: "11",
        complemento: "Bloco C apartamento 25",
        cidade: "Águas Claras",
        bairro: "Arniqueiras",
        uf: "DF",
      },
      {
        nome: "Robert Bessa Gadelha",
        cpf: "7451236589",
        email: "robert@email.com",
        telefone: "99745-7412",
        cep: "72126547",
        logradouro: "Rua 33 Quadra 02",
        numero_lote: "10",
        complemento: "Bloco AB apartamento 10",
        cidade: "Ceilândia",
        bairro: "Ceilândia Norte",
        uf: "DF",
      },
      {
        nome: "Nayma Canela Mourinho",
        cpf: "84559632145",
        email: "nayma@email.com",
        telefone: "99456-4123",
        cep: "72459874",
        logradouro: "Quadra 90",
        numero_lote: "99",
        complemento: "Bloco 4 apartamento 03",
        cidade: "Ceilândia",
        bairro: "Ceilândia Sul",
        uf: "DF",
      },
      {
        nome: "Kira Cantanhede Amado",
        cpf: "45112365984",
        email: "kira@email.com",
        telefone: "99471-6321",
        cep: "72745236",
        logradouro: "Rua 25",
        numero_lote: "55",
        complemento: "Casa",
        cidade: "Taguatinga",
        bairro: "Taguatinga Norte",
        uf: "DF",
      },
      {
        nome: "Melody Tabosa Vasques",
        cpf: "74552369633",
        email: "melody@email.com",
        telefone: "99485-4151",
        cep: "72777856",
        logradouro: "Quadra 10",
        numero_lote: "42",
        complemento: "Casa",
        cidade: "Candangolândia",
        bairro: "",
        uf: "DF",
      },
      {
        nome: "Jeremias Dorneles Rabelo",
        cpf: "45663215987",
        email: "jeremias@email.com",
        telefone: "99126-6213",
        cep: "72745214",
        logradouro: "Avenida dom Quixote Rua 02",
        numero_lote: "36",
        complemento: "Bloco L apartamento 16",
        cidade: "Ceilândia Sul",
        bairro: "Ceilândia",
        uf: "DF",
      },
      {
        nome: "Isabel Viveiros Sanches",
        cpf: "74112030214",
        email: "isabel@email.com",
        telefone: "99666-5555",
        cep: "72111698",
        logradouro: "Rua jabuticaba",
        numero_lote: "12",
        complemento: "Bloco F apartamento 44",
        cidade: "Ceilândia",
        bairro: "Ceilândia Sul",
        uf: "DF",
      },
      {
        nome: "Benjamin Souto Pimenta",
        cpf: "54566322519",
        email: "benjamin@email.com",
        telefone: "99321-1269",
        cep: "72152365",
        logradouro: "Quadra 02",
        numero_lote: "01",
        complemento: "Casa",
        cidade: "Taguatinga",
        bairro: "Taguatinga Norte",
        uf: "DF",
      },
      {
        nome: "Janaína Mirandela Ramires",
        cpf: "41223669852",
        email: "janaina@email.com",
        telefone: "99478-7859",
        cep: "72789654",
        logradouro: "Quadra 90",
        numero_lote: "12",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Ceilândia Norte",
        uf: "DF",
      },
      {
        nome: "Tobias Gameiro Álvaro",
        cpf: "12365478521",
        email: "tobias@email.com",
        telefone: "99165-4163",
        cep: "72149652",
        logradouro: "Rua 890",
        numero_lote: "44",
        complemento: "Casa",
        cidade: "Núcleo Banceirante",
        bairro: "",
        uf: "DF",
      },
      {
        nome: "Nayr Carreira Malho",
        cpf: "12363203214",
        email: "nayr@email.com",
        telefone: "99412-3333",
        cep: "72412036",
        logradouro: "Rua 12",
        numero_lote: "26",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Ceilândia Norte",
        uf: "DF",
      },
      {
        nome: "Evelin Tedim Couceiro",
        cpf: "44456923165",
        email: "evelin@email.com",
        telefone: "99665-4569",
        cep: "72196320",
        logradouro: "Quadra 80 rua 99",
        numero_lote: "13",
        complemento: "Bloco B apartamento 99",
        cidade: "Taguatinga",
        bairro: "Taguatinga Sul",
        uf: "DF",
      },
      {
        nome: "Jael Campos Passos",
        cpf: "11163229651",
        email: "jael@email.com",
        telefone: "99196-4895",
        cep: "72412036",
        logradouro: "Rua 66 Quadra 2",
        numero_lote: "19",
        complemento: "Bloco A apartamento 15",
        cidade: "Taguatinga",
        bairro: "Taguatinga Sul",
        uf: "DF",
      },
      {
        nome: "Leonor Gaspar Oliveira",
        cpf: "12336552014",
        email: "leonor@email.com",
        telefone: "99262-4875",
        cep: "72148596",
        logradouro: "Quada 200 rua 1",
        numero_lote: "26",
        complemento: "Bloco LJ apartamento 02",
        cidade: "Ceilândia",
        bairro: "Setor O",
        uf: "DF",
      },
      {
        nome: "Fernando Salgado Varanda",
        cpf: "14778996321",
        email: "fernado@email.com",
        telefone: "99147-4123",
        cep: "72748514",
        logradouro: "Quadra 900",
        numero_lote: "23",
        complemento: "Bloco MN apartamento 03",
        cidade: "Ceilândia",
        bairro: "P Norte",
        uf: "DF",
      },
      {
        nome: "Lígia Urias Cabral",
        cpf: "14774269874",
        email: "ligia@email.com",
        telefone: "99111-4965",
        cep: "72148596",
        logradouro: "Rua 10",
        numero_lote: "11",
        complemento: "Bloco CL apartamento 01",
        cidade: "Recanto das Emas",
        bairro: "",
        uf: "DF",
      },
      {
        nome: "Josiane Prates Candal",
        cpf: "14203226987",
        email: "josiane@email.com",
        telefone: "99165-4444",
        cep: "72741258",
        logradouro: "Quadra 991",
        numero_lote: "10",
        complemento: "Bloco A apartamento 06",
        cidade: "Taguatinga",
        bairro: "Taguatinga",
        uf: "DF",
      },
      {
        nome: "Maurício Fiães Espargosa",
        cpf: "11169852147",
        email: "mauricio@email.com",
        telefone: "99149-3333",
        cep: "72785963",
        logradouro: "Quadra 441",
        numero_lote: "18",
        complemento: "Bloco A apartamento 55",
        cidade: "Taguatinga",
        bairro: "Taguatinga",
        uf: "DF",
      },
      {
        nome: "Pérola Noronha Patrício",
        cpf: "12336552021",
        email: "perola@email.com",
        telefone: "99888-1010",
        cep: "72412369",
        logradouro: "QNO 29",
        numero_lote: "44",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Ceilândia Sul",
        uf: "DF",
      },
      {
        nome: "Raíssa Caçoilo Murteira",
        cpf: "15996332548",
        email: "raissa@email.com",
        telefone: "99777-1520",
        cep: "72748596",
        logradouro: "QNN 02",
        numero_lote: "98",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Ceilândia Norte",
        uf: "DF",
      },
      {
        nome: "Anderson França Leiria",
        cpf: "11152624158",
        email: "anderson@email.com",
        telefone: "99745-6985",
        cep: "72412365",
        logradouro: "QNE 03",
        numero_lote: "55",
        complemento: "Bloco P apartamento 44",
        cidade: "Vincente Pires",
        bairro: "",
        uf: "DF",
      },
      {
        nome: "Daniel Prudente Aranha",
        cpf: "45663201489",
        email: "daniel@email.com",
        telefone: "99149-4785",
        cep: "72148965",
        logradouro: "QNN 44",
        numero_lote: "18",
        complemento: "Casa",
        cidade: "Brasília",
        bairro: "Asa Sul",
        uf: "DF",
      },
      {
        nome: "Ísis Covilhã Leite",
        cpf: "41226554136",
        email: "isis@email.com",
        telefone: "99416-4965",
        cep: "724414269",
        logradouro: "QNE 77",
        numero_lote: "23",
        complemento: "Casa",
        cidade: "Águas Lindas",
        bairro: "",
        uf: "GO",
      },
      {
        nome: "Zion Alcoforado Olivares",
        cpf: "41223698745",
        email: "zion@email.com",
        telefone: "99745-4896",
        cep: "72454126",
        logradouro: "Rua 89",
        numero_lote: "33",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "Setor O",
        uf: "DF",
      },
      {
        nome: "Letícia Reino Fontoura",
        cpf: "12332165478",
        email: "leticia@email.com",
        telefone: "99963-4874",
        cep: "72145963",
        logradouro: "Quadra 12",
        numero_lote: "32",
        complemento: "Bloco J apartamento 77",
        cidade: "Samambaia sul",
        bairro: "",
        uf: "DF",
      },
      {
        nome: "Brayan Rico Martins",
        cpf: "12669874521",
        email: "brayan@email.com",
        telefone: "99512-4123",
        cep: "72103965",
        logradouro: "Quadra 44",
        numero_lote: "30",
        complemento: "Casa",
        cidade: "Ceilândia",
        bairro: "P Sul",
        uf: "DF",
      },
      {
        nome: "Rebecca Caçoilo Soveral",
        cpf: "12332152036",
        email: "rebecca@email.com",
        telefone: "99123-1489",
        cep: "72494696",
        logradouro: "Rua 65",
        numero_lote: "27",
        complemento: "Bloco A apartamento 80",
        cidade: "Guará 2",
        bairro: "",
        uf: "DF",
      },
      {
        nome: "Hilário Marinho Laureano",
        cpf: "41265423598",
        email: "hilario@email.com",
        telefone: "99162-4103",
        cep: "72412369",
        logradouro: "QNE 90",
        numero_lote: "09",
        complemento: "Casa",
        cidade: "Taguatinga",
        bairro: "Taguatinga",
        uf: "DF",
      },
    ]);
  }
}

module.exports = ClienteSeeder;
